name: TinkLink
targets:
  TinkLink:
    type: framework
    platform: [iOS, macOS]
    info:
      path: Sources/TinkLink/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLink"
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
      MACOSX_DEPLOYMENT_TARGET: 10.13
      MARKETING_VERSION: 0.17.3
      CURRENT_PROJECT_VERSION: 3
    scheme:
      testTargets:
        - name: TinkLinkTests_${platform}
    sources:
      - Sources/TinkLink
    dependencies:
      - carthage: TinkCore
  TinkLinkTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLinkTests"
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
      MACOSX_DEPLOYMENT_TARGET: 10.13
    sources:
      - Tests/TinkLinkTests
    dependencies:
      - target: TinkLink_${platform}
      - carthage: TinkCore
  TinkLinkUI:
    type: framework
    platform: [iOS]
    info:
      path: Sources/TinkLinkUI/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLinkUI"
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
      MARKETING_VERSION: 0.17.3
      CURRENT_PROJECT_VERSION: 3
    scheme:
      testTargets:
        - name: TinkLinkUITests_${platform}
    sources:
      - Sources/TinkLinkUI
    dependencies:
      - target: TinkLink_${platform}
      - carthage: TinkCore
      - carthage: Kingfisher
      - carthage: Down
  TinkLinkUITests:
    type: bundle.unit-test
    platform: [iOS]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLinkUITests"
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
    sources:
      - Tests/TinkLinkUITests
    dependencies:
      - target: TinkLinkUI_${platform}
      - carthage: TinkCore
      - carthage: Kingfisher
      - carthage: Down
  TinkLinkUIUITests:
    type: bundle.ui-testing
    platform: [iOS]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLinkUIUITests"
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
      TEST_TARGET_NAME: "TinkLinkUIUITestsHost_iOS"
    sources:
      - Tests/TinkLinkUIUITests
    dependencies:
      - target: TinkLinkUIUITestsHost_${platform}
      - package: TinkLink
      - package: TinkLinkUI
  TinkLinkUIUITestsHost:
    type: application
    platform: [iOS]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.tink.TinkLinkUIUITestsHost"
      IPHONEOS_DEPLOYMENT_TARGET: 11.0
    sources:
      - Sources/TinkLinkUIUITestsHost
    scheme:
      testTargets:
        - name: TinkLinkUIUITests_${platform}
      environmentVariables:
        TINK_LINK_UI_TESTS_HOST_CLIENT_ID: $TINK_LINK_UI_TESTER_CLIENT_ID
    dependencies:
      - package: TinkLink
      - package: TinkLinkUI
packages:
  TinkLink:
    path: ./
  TinkLinkUI:
    path: ./
